apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: airflow
spec:
  securityContext:
    fsGroup: 50000
  containers:
    - name: debug-container
      image: airflow-kubes:latest
      command: ["sleep", "3600"]
      securityContext:
        runAsUser: 50000
        runAsGroup: 50000
      volumeMounts:
        - name: logs
          mountPath: /opt/airflow/logs
  volumes:
    - name: logs
      emptyDir: {}
  restartPolicy: Never