version: '3.8'

services:
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./output:/opt/airflow/volumes/output
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: webserver
    networks:
      airflow_network:
        aliases:
          - airflow-webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./output:/opt/airflow/volumes/output
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: scheduler
    networks:
      airflow_network:

networks:
  airflow_network:
    driver: bridge