CREATE TABLE IF NOT EXISTS stock_data (
    id SERIAL PRIMARY KEY,
    symbol TEXT NOT NULL,
    open_price DOUBLE PRECISION,
    close_price DOUBLE PRECISION,
    high_price DOUBLE PRECISION,
    low_price DOUBLE PRECISION,
    volume BIGINT,
    date TIMESTAMP NOT NULL,
    sma_10 DOUBLE PRECISION,
    sma_50 DOUBLE PRECISION,
    rsi DOUBLE PRECISION,
    macd DOUBLE PRECISION,
    signal DOUBLE PRECISION,
    buy_signal BOOLEAN,
    sma_20 DOUBLE PRECISION,
    ema_12 DOUBLE PRECISION,
    ema_26 DOUBLE PRECISION,
    buy_signal_short BOOLEAN,
    buy_signal_long BOOLEAN,
    buy_signal_longer BOOLEAN,
    buy_prob_ml_short DOUBLE PRECISION,
    buy_prob_ml_medium DOUBLE PRECISION,
    buy_prob_ml_long DOUBLE PRECISION,
    buy_ml_short BOOLEAN,
    buy_ml_medium BOOLEAN,
    buy_ml_long BOOLEAN
);
